DROP TABLE IF EXISTS AGGREGATE_EXAMPLE;
DROP TABLE IF EXISTS JSONEVENTS;

CREATE TABLE AGGREGATE_EXAMPLE(
    id INTEGER primary key not null, 
    status varchar(255)
);

CREATE TABLE JSONEVENTS(
    id BIGSERIAL PRIMARY KEY,
    val JSONB NOT NULL
);